[package]
name = "as5600-async-mock-example"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
# We point to the local crate with 'async' and 'mock' features
AS5600-Driver = { path = "../../", features = ["async", "mock", "anyhow"] }
anyhow = "1.0"
tokio = { version = "1.52.3", features = ["full"] }
